class ConstantManager {
  static const String welcomeMessage = "Welcome Back To Route";
  static const String askForSignIn = "Please sign in with your email";
  static const String noWorries =
      "No worries,we will send you reset instructions.";
  static const String email = "E=mail address";
  static const String emailLabel = "enter your e-mail address ";
  static const String password = "Password ";
  static const String passwordLabel = "Password";
  static const String forgetPassword = "Forget password ?";
  static const String resetPassword = "Reset password";
  static const String backToLogin = "Back to login";
  static const String login = "Login";
  static const String failed = "Failed";
  static const String dontHaveAccount = "Don't have an account ?";
  static const String createAccount = "Create account";
  static const String signUp = "Sign up";
  static const String fullName = "Full Name";
  static const String fullNameLabel = "enter your full name";
  static const String phoneNumber = "Phone Number";
  static const String phoneNumberLabel = "enter you phone number";
  static const String confirmPassword = "Confirm Password";
  static const String confirmPasswordLabel = "enter your confirm password";
  static const String loading = "Loading...";
  static const String waiting = "Waiting...";
  static const String ok = "ok";
  static const String back = "Back";
  static const String category = "Categories";
  static const String brand = "Brands";
  static const String passwordReset = "Password Reset.";
  static const String weSentCode = "We sent a code to ";
  static const String Continue = "Continue ";
  static const String didntReceiveEmail = "Didn't receive the email ?";
  static const String clickHere = "Click here";
  static const String viewAll = "view all";
  static const String notNow = "Not Now";
  static const String saveLogin = "want to save your login ?";
  static const String loginSuccess = "Login Successfully";
  static const String createdSuccess = "Account created Successfully";
  static const String home = "home";
  static const String shop = "shop";
  static const String favourite = "favourite";
  static const String personal = "personal";
  static const String searchFor = "what do you search for ?";
  static const String token = "token";
  static const String keepLogin = "keepLogin";
  static const String productDetails = "Product Details";
  static const String cart = "Cart";
  static const String addToCart = "Add to cart";
  static const String description = "Description";
  static const String size = "Size";
  static const String color = "Color";
  static const String totalItemPrice = "Total Item price";
  static const String checkOut = "Checkout";
  static const String chooseAmount = "Choose amount";
  static const String setNewPassword = "Set new password";
  static const String atLeast = "Must be at least 8 charaters.";
  static const String passwordReseted = "Password reset successfully ";
}

class EndPoint {
  static const String baseUrl = "https://ecommerce.routemisr.com";
  static const String signUpEndPoint = "/api/v1/auth/signup";
  static const String loginEndPoint = "/api/v1/auth/signin";
  static const String categoriesEndPoint = "/api/v1/categories";
  static const String brandsEndPoint = "/api/v1/brands";
  static const String productsEndPoint = "/api/v1/products";
  static const String addToCart = "/api/v1/cart";
  static const String addToWatchList = "/api/v1/wishlist";
  static const String forgetPassword = "/api/v1/auth/forgotPasswords";
  static const String restCode = "/api/v1/auth/verifyResetCode";
  static const String resetPassword = "/api/v1/auth/resetPassword";
}
